### ISSUE TITLE
nova_keypair, NameError: global name 'nova_client' is not defined

### ISSUE THREAD

**Issue by ccollicutt** [openstack-ansible/openstack-ansible#19]
I will try to figure this out...but if it's anything obvious let me know. :)

All I did was clone the repo, git submodule update --init,  and run make.

```bash
TASK: [capture public key in variable] **************************************** 
changed: [controller]

TASK: [add ssh keypair to nova] *********************************************** 
fatal: [controller] => failed to parse: Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1396833154.9-61665095293347/nova_keypair", line 1208, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1396833154.9-61665095293347/nova_keypair", line 103, in main
    nova = nova_client.Client(module.params['login_username'],
NameError: global name 'nova_client' is not defined


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/curtis/demo.yaml.retry

controller                 : ok=13   changed=4    unreachable=1    failed=0   

make: *** [demo] Error 3
```

**Comment by alvico** [comment]
I'm having this same issue with:

ansible 1.8.4

**Comment by mcameron** [comment]
+1

**Comment by mcameron** [comment]
Removing localhost from my dynamic inventory fixed this for me.

**Comment by mcameron** [comment]
Additionally, ansible-1.8.4 installed with brew on OSX exhibits this issue, even when localhost is not included in my dynamic inventory.

Ansible-1.8.4 installed with pip (brew remove ansible, resource bashrc) and no localhost in the dynamic inventory works A-OK.

**Comment by devth** [comment]
I'm running this as a local_action. On ansible `1.9.0.1`, I still get `global name 'nova_client' is not defined`. I've installed a few versions of python-novaclient (2.6.0, 2.23.0).

**Comment by devth** [comment]
Update: I had installed ansible with homebrew before. I uninstalled it, then re-installed with `easy_install`, then it worked. Not sure why homebrew even has ansible :older_man:
